#!/bin/sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
DIST=${DIST_DIR:-"$ROOT/dist"}
mkdir -p "$DIST"

# Prefer Syft when a release workstation has it. The fallback remains useful
# in the small build image: Go's module graph is a deterministic SBOM input
# and is stored verbatim rather than pretending that a partial license scan is
# complete.
if command -v syft >/dev/null 2>&1; then
	syft "dir:$ROOT" -o spdx-json > "$DIST/sbom.spdx.json"
	printf '%s\n' "SBOM generated by syft" > "$DIST/sbom provenance.txt"
elif command -v go >/dev/null 2>&1; then
	go list -m -json all > "$DIST/sbom.go-modules.json"
	printf '%s\n' "SBOM fallback: go list -m -json all; run syft for SPDX output" > "$DIST/sbom provenance.txt"
else
	awk 'BEGIN { print "{\"format\":\"go-module-manifest\",\"modules\":["; first=1 } /^module / { if (!first) print ","; printf "{\"path\":\"%s\"}", $2; first=0 } END { print "]}" }' "$ROOT/go.mod" > "$DIST/sbom.go-modules.json"
	printf '%s\n' "SBOM fallback: go.mod manifest; run syft or go list for full output" > "$DIST/sbom provenance.txt"
fi
echo "SBOM written to $DIST"
